steps:
  # Step 1: Pull the Docker image and build using the Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/canvas-app', '.']
    # Substitute your repo URL
    dir: "github-repo-directory"
    # Push the image to the Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/canvas-app']
    timeout: '3200s'  # Adjust based on your build time (Canvas LMS build can be long)

images:
  # Specify the output image in GCR
  - 'gcr.io/$PROJECT_ID/canvas-app'
