default: &default
  domain: <%= ENV.fetch('CANVAS_LMS_DOMAIN') %>

production:
  <<: <%= ENV.fetch('CANVAS_LMS_DOMAIN') %>

development:
  <<: <%= ENV.fetch('CANVAS_LMS_DOMAIN') %>

test:
  <<: <%= ENV.fetch('CANVAS_LMS_DOMAIN') %>
